version: '3'
services: 
  web:
    build: .
    container_name: api-python
    ports: 
      - 3000:80
    links: 
      - redis
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis-db